name: Mirror @ Murcia Organization

on:
  push:
    branches:
      master
  delete:
    branches:
      master

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2-beta
      with:
        repository: weso/repo-synchronizer-action
        token: ${{ secrets.WESOBOT_ACCESS_TOKEN }}
    - name: repo-sync
      uses: ./
      env:
        SOURCE_REPO: "git@github.com:weso/shEx2Code.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: "git@github.com:HerculesCRUE/ib-Shex2Code.git"
        DESTINATION_BRANCH: "master"
        SSH_PRIVATE_KEY: ${{ secrets.IZERTIS_GITHUB_SSH_KEY }}
      with:
         args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH

